/* 조합 1안 · 부품/카드 — 자동화① 목록 카드. 손질/07_콘텐츠 랩 조합(2026-10-03) · 만든 이: 손질/07_콘텐츠/1안반영.py — 여기 직접 고치지 말 것 */
(function(){var d=document;try{if(frameElement&&frameElement.id==='판'&&/손질후\.html$/.test(decodeURIComponent(parent.location.pathname)))return;}catch(e){}if(window.__1안카드)return;window.__1안카드=1;var 됨=0;function 시작(){if(됨||!d.querySelector('.grid > .wf-card'))return;됨=1;d.documentElement.classList.add('lab-카드');try{(function(){if(window.__lab스위치)return;window.__lab스위치=1;var D=document;
D.addEventListener('click',function(e){var s=e.target.closest&&e.target.closest('.wf-card .bot .switch-demo');if(!s||s.classList.contains('is-disabled'))return;
 var c=s.closest('.wf-card');if(!c||!/^(wait|off)$/.test(c.dataset.state))return;e.preventDefault();e.stopPropagation();
 var 켬=!s.classList.contains('is-on'),nm=c.querySelector('.nowbox .nm'),sub=c.querySelector('.nowbox .sub');
 if(nm&&!c.dataset.lab처음){c.dataset.lab처음=c.dataset.state;c.dataset.lab글=nm.textContent;c.dataset.lab덧글=sub?sub.textContent:'';}
 s.classList.toggle('is-on',켬);var 처음=c.dataset.lab처음;
 if(켬){c.dataset.state=처음==='off'?'wait':처음;if(nm){nm.textContent=처음==='off'?'다음 실행':c.dataset.lab글;}if(sub)sub.textContent=처음==='off'?'켜짐 · 일정대로 돎':c.dataset.lab덧글;}
 else{c.dataset.state='off';if(nm)nm.textContent='꺼져 있음';if(sub)sub.textContent=처음==='off'?c.dataset.lab덧글:'켜면 다시 돎';}
},true);})();}catch(e){}try{(function(){var D=document,번=0;function 달기(){var 다시=false;D.querySelectorAll('.grid > .wf-card').forEach(function(c){var r=c.querySelector('.c-row');if(!r||r.querySelector('.lab머리'))return;
 var 줄찾기=function(t){return [].find.call(D.querySelectorAll('.lnb-panel .channel-text-demo'),function(x){var l=x.querySelector('.ch-label');return l&&l.textContent.trim()===t;});}; var 줄=줄찾기(c.dataset.t);if(!줄){var 같은=[].find.call(D.querySelectorAll('.grid > .wf-card'),function(x){return x!==c&&x.dataset.kind===c.dataset.kind&&x.dataset.state!=='setup'&&줄찾기(x.dataset.t);});if(같은)줄=줄찾기(같은.dataset.t);}
 var h=D.createElement('span');h.className='lab머리';var g=D.createElement('span');g.className='lab머리그림';h.appendChild(g);
 var d=줄&&줄.querySelector('.lab-대체');if(d){var 보임=[].find.call(d.children,function(x){return x.tagName!=='I'&&getComputedStyle(x).display!=='none';});
  if(보임){var b=getComputedStyle(보임,'::before'),m=b.webkitMaskImage||b.maskImage;if(m&&m!=='none'){g.classList.add('마스크');g.style.webkitMaskImage=m;g.style.maskImage=m;}
   else{var sv=[].find.call(보임.querySelectorAll('svg'),function(x){return getComputedStyle(x).display!=='none';});if(sv)g.appendChild(sv.cloneNode(true));}}
  var i=d.querySelector('i');if(i){var j=D.createElement('i'),s=getComputedStyle(i);j.className=i.className;j.style.backgroundImage=s.backgroundImage;j.style.backgroundColor=s.backgroundColor;h.appendChild(j);}}
 if(!g.firstChild&&!g.classList.contains('마스크')){다시=true;return;}r.insertBefore(h,r.firstChild);});if(다시&&번++<15)setTimeout(달기,200);}
var n=0;(function 기다림(){if(!D.querySelector('.lnb-panel .lab-대체')&&n++<30)return setTimeout(기다림,100);달기();})();
if(!window.__lab머리감시){window.__lab머리감시=1;new MutationObserver(function(){달기();}).observe(D.querySelector('.content')||D.body,{childList:true,subtree:true});}})();(function(){var D=document;function 달기(){D.querySelectorAll('.grid > .wf-card').forEach(function(c){var b=c.querySelector('.bot');if(!b||b.querySelector('.lab지금'))return;
 var n=c.querySelector('.n.cur, .n.retry, .n.fail, .n.waitc, .n.waitp');if(!n)return;var m=(n.dataset.tip||'').match(/^\s*\d+\/\d+\s+(.+?)\s+—/);if(!m)return;
 var 실패=n.classList.contains('fail'),끝=실패?'에 실패했습니다':n.classList.contains('retry')?' 재시도 중입니다':/wait/.test(n.className)?' 기다리는 중입니다':' 중입니다';
 var s=D.createElement('span');s.className='lab지금'+(실패?' 실패':'');s.textContent=m[1]+끝;var 글=b.querySelector('.nowbox');if(글&&글.dataset.full)s.title=글.dataset.full;b.insertBefore(s,b.firstChild);});}
D.querySelectorAll('.grid > .wf-card[data-state=setup] .bot .acts').forEach(function(a){if(a.querySelector('.lab설정'))return;var b=D.createElement('button');b.className='run-btn lab설정';b.textContent='설정';a.appendChild(b);});달기();if(!window.__lab지금감시){window.__lab지금감시=1;new MutationObserver(function(){달기();}).observe(D.querySelector('.content')||D.body,{childList:true,subtree:true});}})();(function(){var D=document,번=0;
var 시계='<svg class="lab반전그림" viewBox="0 0 20 20" aria-hidden="true"><circle cx="10" cy="10" r="7.6" fill="#fff"/><path class="바늘 짧은" d="M10 10V6.4" stroke="#16a34a" stroke-width="1.5" stroke-linecap="round"/><path class="바늘 긴" d="M10 10l2.9 1.7" stroke="#16a34a" stroke-width="1.5" stroke-linecap="round"/></svg>';
var 갈래='<svg class="lab반전그림" viewBox="0 0 20 20" fill="none" aria-hidden="true"><path class="갈래선" d="M6.167 7.333v5.778m0-2.889h5.778c1.01 0 1.516 0 1.902-.197.34-.173.616-.45.79-.789.196-.386.196-.892.196-1.903" stroke="#fff" stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round"/><path class="흐름 왼" d="M6.167 15.277V5.167" stroke="#fff" stroke-width="1.6" stroke-linecap="round" fill="none"/><path class="흐름 오" d="M6.167 15.277v-5.055h5.778c1.01 0 1.516 0 1.902-.197.34-.173.616-.45.79-.789.196-.386.196-.892.196-1.903V5.167" stroke="#fff" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" fill="none"/><circle class="원" cx="6.167" cy="5.167" r="2.17" fill="#fff"/><circle class="원" cx="14.833" cy="5.167" r="2.17" fill="#fff"/><circle class="원" cx="6.167" cy="15.277" r="2.17" fill="#fff"/></svg>';
var 선시계='<svg class="lab선그림" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-linecap="round" aria-hidden="true"><circle cx="10" cy="10" r="8.3" stroke-width="1.25"/><path class="바늘 짧은" d="M10 10V5.8" stroke-width="1.3"/><path class="바늘 긴" d="M10 10l3.3 1.9" stroke-width="1.3"/></svg>';
var 선갈래='<svg class="lab선그림" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><g class="갈래선" stroke-width="1.25"><circle cx="6.167" cy="5.167" r="2.1"/><circle cx="14.833" cy="5.167" r="2.1"/><circle cx="6.167" cy="15.277" r="2.1"/><path d="M6.167 7.267v5.91m0-2.955h5.778c1.01 0 1.516 0 1.902-.197.34-.173.616-.45.79-.789.196-.386.196-.892.196-1.903"/></g><path class="흐름 왼" d="M6.167 15.277V5.167" stroke-width="1.6" stroke-linecap="round" fill="none"/><path class="흐름 오" d="M6.167 15.277v-5.055h5.778c1.01 0 1.516 0 1.902-.197.34-.173.616-.45.79-.789.196-.386.196-.892.196-1.903V5.167" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" fill="none"/></svg>';
function 달기(){var 남음=false;D.querySelectorAll('.grid > .wf-card').forEach(function(c){if(!c.querySelector('.n.cur, .n.retry')&&!(c.dataset.kind==='자동'&&c.dataset.state==='wait'))return;var h=c.querySelector('.lab머리');if(!h){남음=true;return;}if(h.querySelector('.lab반전그림'))return;
 h.insertAdjacentHTML('afterbegin',(c.dataset.kind==='수동'?갈래:시계)+(c.dataset.kind==='수동'?선갈래:선시계));});if(남음&&번++<20)setTimeout(달기,200);}
달기();if(!window.__lab반전감시){window.__lab반전감시=1;new MutationObserver(function(){달기();}).observe(D.querySelector('.content')||D.body,{childList:true,subtree:true});}})();}catch(e){}try{(function(){var D=document;function 달기(){D.querySelectorAll('.grid > .wf-card').forEach(function(c){if(!c.querySelector('.n.cur, .n.retry'))return;var s=c.querySelector('.lab지금');if(!s||s.querySelector('.lab점'))return;
 s.textContent=s.textContent.replace(/\s*입니다$/,'');s.insertAdjacentHTML('beforeend','<span class="lab점" aria-hidden="true"><i></i><i></i><i></i></span>');});}
var 번=0;(function 기다림(){달기();if(번++<20)setTimeout(기다림,200);})();
if(!window.__lab점감시){window.__lab점감시=1;new MutationObserver(function(){달기();}).observe(D.querySelector('.content')||D.body,{childList:true,subtree:true});}})();}catch(e){}try{(function(){var D=document;
function 지금(s){return s.replace(/\s*중입니다$/,' 중').replace(/에 실패했습니다$/,' 실패').replace(/\s*기다리는 중입니다$/,' 대기');}
function 쉼(nm,sub){var m;
 if(nm==='최근 실행'&&(m=sub.match(/^(.+?)\s*·\s*(완료|실패|중지)$/)))return '최근 실행 '+m[2]+' · '+m[1];
 if(/올라옴 대기$/.test(nm)&&(m=sub.match(/^지식함\s*(.+?)\s*폴더$/)))return '문서 업로드 시 실행 · 지식함 '+m[1];
 if(nm==='꺼져 있음'&&(m=sub.match(/^켜면\s*(.+?)에 시작$/)))return m[1]+' 실행';
 if(nm==='설정 중'&&(m=sub.match(/^(.+?)[을를] 채우면/)))return m[1]+' 필요';
 if(nm==='설정 중'&&(m=sub.match(/^(.+?)[을를] 정하면/)))return m[1]+' 지정 필요';
 if(nm==='다음 실행'&&sub)return '다음 실행 · '+sub;
 return sub?nm+' · '+sub:null;}
function 달기(){D.querySelectorAll('.grid > .wf-card').forEach(function(c){
 var j=c.querySelector('.lab지금');if(j&&!j.dataset.lab기계){j.dataset.lab기계=1;var 점=j.querySelector('.lab점');var t=지금(j.firstChild&&j.firstChild.nodeType===3?j.firstChild.nodeValue:j.textContent);
  if(j.firstChild&&j.firstChild.nodeType===3)j.firstChild.nodeValue=t;else j.textContent=t;if(점&&!j.contains(점))j.appendChild(점);}
 var b=c.querySelector('.bot .nowbox');if(!b||b.dataset.lab기계)return;var nm=b.querySelector('.nm'),sub=b.querySelector('.sub');if(!nm)return;
 var 새=쉼(nm.textContent.trim(),sub?sub.textContent.trim():'');b.dataset.lab기계=1;if(새==null)return;nm.textContent=새;if(sub)sub.textContent='';});}
var 번=0;(function 기다림(){달기();if(번++<20)setTimeout(기다림,200);})();
if(!window.__lab기계감시){window.__lab기계감시=1;new MutationObserver(function(){달기();}).observe(D.querySelector('.content')||D.body,{childList:true,subtree:true});}})();}catch(e){}try{(function(){if(window.__긴글)return;window.__긴글=1;var D=document,풍선=null,지금=null;
function 대상(카드){var b=카드.querySelector('.bot');if(!b)return null;var ks=[].filter.call(b.children,function(k){return !k.classList.contains('acts')&&getComputedStyle(k).display!=='none';});var el=ks[0]||null;if(el&&el.classList.contains('nowbox')){var 후=[].filter.call(el.querySelectorAll(':scope > .nm, :scope > .sub'),function(k){return k.textContent.trim();});후.sort(function(x,y){return (y.scrollWidth-y.clientWidth)-(x.scrollWidth-x.clientWidth);});el=후[0]||el;}return el;}
function 방식(el){return (getComputedStyle(el).getPropertyValue('--lab긴글')||'').trim();}
function 넘침(el){return el.scrollWidth-el.clientWidth;}
function 제목걷기(카드){var b=카드.querySelector('.bot');if(!b)return;var 첫=b.querySelector('.lab지금, .nowbox > .nm, .nowbox > .sub');if(!첫||!방식(첫))return;[].forEach.call(b.querySelectorAll('[title]'),function(x){x.dataset.lab제목=x.title;x.removeAttribute('title');});}
function 제목되돌림(카드){if(!카드)return;[].forEach.call(카드.querySelectorAll('[data-lab제목]'),function(x){x.title=x.dataset.lab제목;delete x.dataset.lab제목;});}
D.addEventListener('mouseover',function(e){var 카드=e.target.closest&&e.target.closest('.wf-card');if(카드)제목걷기(카드);if(!카드||카드===지금)return;떠남();지금=카드;var el=대상(카드);if(!el)return;var m=방식(el),n=넘침(el);
 if(m==='flow'&&n>2){var 안=el.querySelector(':scope > .lab흐름안');if(!안){안=D.createElement('span');안.className='lab흐름안';while(el.firstChild)안.appendChild(el.firstChild);el.appendChild(안);}n=안.scrollWidth-el.clientWidth;if(n<=2)return;el.classList.add('lab흐르는');var t=Math.max(.6,n/40);안.style.transition='transform '+t+'s linear .35s';안.style.transform='translateX('+(-n)+'px)';카드.__흐름=el;}
});
D.addEventListener('mouseover',function(e){var el=e.target.closest&&e.target.closest('.wf-card .bot > .lab지금, .wf-card .bot > .nowbox > .nm, .wf-card .bot > .nowbox > .sub');var 판=el&&방식(el);if(!el||(판!=='tip'&&판!=='tipc')||넘침(el)<=2){if(풍선&&!(e.target.closest&&e.target.closest('.wf-card .bot')))풍선.classList.remove('보임');return;}
 if(!풍선){풍선=D.createElement('div');풍선.className='lab긴글풍선';D.body.appendChild(풍선);}풍선.textContent=el.textContent.replace(/\s+/g,' ').trim();var r=el.getBoundingClientRect();풍선.style.maxWidth='';풍선.style.left=Math.max(8,r.left)+'px';if(판==='tipc'){var 카=el.closest('.wf-card').getBoundingClientRect();풍선.style.maxWidth=Math.min(320,카.width-16)+'px';var 너=풍선.getBoundingClientRect().width;풍선.style.left=Math.round(카.left+카.width/2-너/2)+'px';}풍선.style.top='0px';풍선.classList.add('보임');풍선.style.top=(r.bottom+6)+'px';});
function 떠남(){if(풍선)풍선.classList.remove('보임');제목되돌림(지금);if(지금&&지금.__흐름){var el=지금.__흐름,안=el.querySelector(':scope > .lab흐름안');if(안){안.style.transition='transform .2s ease-out';안.style.transform='translateX(0)';setTimeout(function(){if(안.style.transform==='translateX(0px)'||안.style.transform==='translateX(0)'){while(안.firstChild)el.insertBefore(안.firstChild,안);안.remove();el.classList.remove('lab흐르는');}},230);}지금.__흐름=null;}지금=null;}
D.addEventListener('mouseout',function(e){if(!지금)return;var to=e.relatedTarget;if(to&&지금.contains(to))return;if(e.target.closest&&e.target.closest('.wf-card')===지금)떠남();});})();}catch(e){}}시작();if(!됨){var 관=new MutationObserver(function(){시작();if(됨)관.disconnect();});관.observe(d.body||d.documentElement,{childList:true,subtree:true});}})();
